config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :users

  resources :services do
    resources :bookings
  end

  get "bookings", to: "bookings#index", as: :bookings
  get 'landing', to: 'services#landing'
  get 'requests', to: 'services#requests'
  resources :bookings, only: [] do
    resources :messages, only: [:create]
    resources :reviews, except: [:index]
    member do
      patch :accept
      patch :reject
    end
    resources :activities
  end

  resources :pets
  get 'conversation/:id', to: 'conversations#show', as: :conversation
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings, dependent: :destroy
  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :specie, inclusion: { in: %w[Dog Cat Rodent Bird Reptile Others] }, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :address, presence: true, length: { maximum: 200 }
  #validates :photo, presence: true
  validates :restrictions, presence: true, length: { maximum: 200 }
  validates :house_description, presence: true, length: { maximum: 500 }

  def recent_reviews(limit = 3)
    reviews.order(created_at: :desc).limit(limit)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # before_action :set_user
  before_action :set_service, only: %i[show edit update destroy]
  before_action :set_services_and_bookings, only: %i[index requests]

  def index
    @services = Service.where(user: current_user)
    @bookings = @services.map(&:bookings).flatten
    ## Get users
    @users = User.all
  end

  def requests
    @bookings_pending = @bookings.reverse.select { |booking| booking.status == "pending" }
    @bookings_confirmed = @bookings.reverse.select { |booking| booking.status == "confirmed" }
    @bookings_reject = @bookings.reverse.select { |booking| booking.status == "rejected" }
    @users = User.all
  end

  def landing
    @services = Service.all
    @services = if params[:specie]
                  Service.where(specie: params[:specie])
                else
                  Service.all
                end
    if params[:query].present?
      @services = @services.where('address ILIKE ?', "%#{params[:query]}%")
      # @services = @services.where(address: params[:query])
    end
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.user_id = current_user.id
    if @service.save
      redirect_to @service, notice: '🎉 Your service was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @marker = {
      lat: @service.latitude,
      lng: @service.longitude,
      info_window_html: render_to_string(partial: "info_window", locals: { service: @service })
    }
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to @service, notice: '🎉 Your service was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @service.destroy!
    redirect_to services_path, notice: '😔 Your service was successfully deleted.'
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:price, :description, :address, :specie, :restrictions, :house_description, :photo, :longitude, :latitude)
  end

  def set_services_and_bookings
    @services = Service.where(user: current_user)
    @bookings = @services.flat_map(&:bookings)
  end
end

app/views/services/_info_window.html.erb
<div>
  <i class="fa-solid fa-location-dot icon-custom"></i>
  <strong>Address:</strong>
  <%= @service.address %>
</div>

app/views/services/_services_list.html.erb
<div class="r-added-cards">
  <% if services.any? %>
    <% services.reverse.each do |service| %>
      <%= link_to service_path(service), class: "card-link" do %>
        <div class="card-service">
          <%= cl_image_tag service.photo.key, height: 300, width: 400, crop: :fill %>
          <div class="card-service-infos pb-3">
            <div>
              <div class="d-flex py-1 align-items-center">
                <%= cl_image_tag service.user.photo.key, class: "avatar mx-2", alt: "dropdown menu", crop: :fill %>
                <h2><%= service.user.first_name %> <%= service.user.last_name %></h2>
              </div>
              <h4 class="pt-3 pb-1 m-0">Takes care of a: <strong style="color: #FD8522"><%= service.specie %></strong></h4>
              <p><%= service.address %></p>
            </div>
          </div>
          <div class="d-flex pb-3">
            <h2 class="ms-auto me-4">$ <%= service.price %> per day</h2>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <em>Sorry, no sitters found.</em>
  <% end %>

app/views/services/edit.html.erb
<div class="bg-white">
  <div class="container p-4">
    <div class="row g-0 justify-content-center align-items-stretch">

      <div class="col-md-5 d-flex flex-column rounded shadow bg-light p-4">
        <h1 class="mb-4 text-center">Edit this Service</h1>
        <%= simple_form_for([@user, @service], html: {data: {turbo: false}} ) do |f| %>
          <% if @service.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>
              <ul>
                <% @service.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.input :specie, as: :select, collection: %w[Dog Cat Rodent Bird Reptile Others], prompt: 'Select a specie', label: 'What kind of pet are you sitting?', label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :price, as: :string, label: "What's the price per day?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :description, label: 'Tell us more about the service', label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.hidden_field :latitude %>
            <%= f.hidden_field :longitude %>
            <%= f.input :address,
                        required: true,
                        label: "What is the address where the pet will be cared for?",
                        label_html: { class: 'form-label' },
                        wrapper_html: {
                          data: {
                            controller: 'address-autocomplete',
                            address_autocomplete_api_key_value: ENV['MAPBOX_API_KEY'],
                            address_autocomplete_search_value: @service.address
                          }
                        },
                        input_html: {
                          data: { address_autocomplete_target: 'address' },
                          class: 'd-none form-control',
                          style: 'font-size: 14px;',
                          } %>
          </div>

          <div class="form-group">
            <%= f.input :restrictions, label: "What are your restrictions as a caregiver?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :house_description, label: "Tell us more about your place", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :photo, label: "Please load a photo related to your service", as: :file, required: true, label_html: { class: 'form-label' }, input_html: { class: 'form-control-file', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group text-center d-grid">
            <%= f.button :submit, 'Save', class: 'btn btn-warning text-white' %>
          </div>
        <% end %>
      </div>

      <div class="col-md-5 d-flex rounded shadow p-4" style="
        background-image: url('<%= asset_path 'care1.jpeg' %>');
        background-size: cover;
        background-position: center;">
      </div>

    </div>
  </div>
</div>

app/views/services/index.html.erb
<div class="bg-white">
  <div class="container pb-4">
    <div class="d-flex justify-content-between align-items-center my-4">
      <h1 class="text-center">My offered <span class="fw-bold" style= 'color: #FD8522'>Services</span></h1>
      <div class="text-center">
        <%= link_to new_service_path, class: 'mt-3 btn text-white rounded-pill px-4 py-2', style: "background-color: #FD8522;" do %>
          <i class="fa-solid fa-plus"></i> Add New Service
        <% end %>
      </div>
    </div>
    <div class="row">
      <% @services.reverse.each do |service| %>
        <div class="col-lg-12">
        <div class="card-custom card bg-white shadow-lg mb-3 border border-1 p-0">
          <div class="card card-body bg-white d-flex flex-row justify-content-between align-items-center">
            <p class="m-0">
            <strong style="color: #FD8522">Created at: <%= service.created_at.strftime("%B %d, %Y") %>
            </strong></p>
            <div class="d-flex">
                  <%= link_to edit_service_path(service), class: 'px-3 me-2', style: 'color: #FD8522; font-size: 24px;' do %>
                    <i class="fa-solid fa-pen-to-square"></i>
                  <% end %>


                   <%= link_to service, data: { turbo_method: :delete, bs_toggle: "modal", bs_target: "#serviceModal" }, class: 'px-3', style: 'color: #FD8522; font-size: 24px;'  do %>
                      <i class="fa-solid fa-trash"></i>
                    <% end %>


                <!-- Modal -->
                  <div class="modal fade" id="serviceModal" tabindex="-1" aria-labelledby="serviceModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title text-center" id="serviceModalLabel">Are you sure?</h5>
                          </div>
                          <div class="modal-body">
                            <strong><%= current_user.first_name %></strong> you're about to delete this service
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn rounded-pill btn-secondary" data-bs-dismiss="modal">Close</button>
                            <%= link_to service, data: { turbo_method: :delete }, class: 'px-3', style: 'color: #FD8522; font-size: 24px;'  do %>
                              <span class="btn rounded-pill btn-warning text-white">Delete</span>
                            <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                <!-- Modal -->



                </div>
          </div>
          <div class="card card-body"  style="background-color: white;">
            <div class="row d-flex justify-content-between align-items-center">
              <div class="col-3 d-flex justify-content-center align-items-center">
                <%= cl_image_tag service.photo.key, crop: :fill, class: "w-100" %>
              </div>
              <div class="col-9 d-flex flex-column justify-content-center gap-3">
                <p class="m-0">"<%= service.description %>"</p>
                <p class="m-0"><strong>Price per day:</strong> $<%= service.price %></p>
                <p class="m-0"><strong ><i class="fa-solid fa-location-dot"></i>&nbsp; The address where you will provide the service in: </strong><%= service.address %></p>
                <p class="m-0"><strong><i class="fa-solid fa-notdef"></i>&nbsp; Your restrictions as a caregiver:</strong>&nbsp; <%= service.restrictions %></p>
                <p class="m-0"><strong><i class="fa-solid fa-house"></i>&nbsp; Your place description:</strong>&nbsp; <%= service.house_description %> </p>

              </div>
            </div>
          </div>
        </div>
        </div>
      <% end %>
    </div>


  </div>
</div>

app/views/services/landing.html.erb
<div style="background-color: white;">
  <%# SEARCH %>
  <div class="mb-4">
    <%= form_with url: landing_path, method: :get, class: "d-flex justify-content-center", data: { turbo_frame: "services_frame" } do %>
      <%= text_field_tag :query, params[:query], class: "form-control me-2 rounded-pill", placeholder: "Search by address", style: "max-width: 500px; font-size: 14px;" %>
      <%= submit_tag "Search", class: "btn rounded-pill text-white", style: "background-color: #fd8522" %>
    <% end %>
  </div>
  <%# SEARCH %>

  <div class="container pb-5">
    <h2 class="py-3 text-center">Find your ideal <span class="fw-bold" style="color: #FD8522">Pet Sitter</span></h2>
    <div class="row pb-5 mt-4">
      <div class="col-2">
        <%= link_to landing_path(specie: 'Dog'), class: 'card-link' do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'dog.png' %>); transition: 0.25s ease ">
            Dogs
          </div>
        <% end %>
      </div>
      <div class="col-2">
        <%= link_to landing_path(specie: 'Cat'), class: 'card-link' do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'cat.jpg' %>); transition: 0.25s ease">
            Cats
          </div>
        <% end %>
      </div>
      <div class="col-2">
        <%= link_to landing_path(specie: 'Rodent'), class: 'card-link' do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'rabbit.png' %>); transition: 0.25s ease">
            Rodents
          </div>
        <% end %>
      </div>
      <div class="col-2">
        <%= link_to landing_path(specie: 'Bird'), class: 'card-link' do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'bird2.png' %>); transition: 0.25s ease">
            Birds
          </div>
        <% end %>
      </div>
      <div class="col-2">
        <%= link_to landing_path(specie: 'Reptile'), class: 'card-link' do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'reptile.png' %>); transition: 0.25s ease">
            Reptiles
          </div>
        <% end %>
      </div>
      <div class="col-2">
        <%= link_to landing_path(specie: 'Others'), class: 'card-link' do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'fish.png' %>); transition: 0.25s ease">
            Others
          </div>
        <% end %>
      </div>
    </div>

    <%# Turbo Frame for services %>

      <div class="r-added-cards">
        <% if @services.any? %>
          <% @services.reverse.each do |service| %>
            <%= link_to service_path(service), class: "card-link" do %>
              <div class="card-service h-100">
                <%= cl_image_tag service.photo.key, height: 300, width: 400, crop: :fill %>
                <div class="card-service-infos pb-3">
                  <div>
                    <div class="d-flex py-1 align-items-center">
                      <%= cl_image_tag service.user.photo.key, class: "avatar mx-2", alt: "service provider photo", crop: :fill, height: 40, style: "object-fit: cover;" %>
                      <h2><%= service.user.first_name %> <%= service.user.last_name %></h2>
                    </div>
                    <h4 class="pt-3 pb-1 m-0">Takes care of a: <strong style="color: #FD8522"><%= service.specie %></strong></h4>
                    <p><%= service.address %></p>
                  </div>
                </div>
                <div class="d-flex pb-3">
                  <h2 class="ms-auto me-4">$ <%= service.price %> per day</h2>
                </div>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <em>Sorry, no sitters found.</em>
        <% end %>
      </div>

  </div>
</div>

app/views/services/landing.turbo_stream.erb
<%= turbo_stream.replace "services_frame" do %>
  <%= render partial: "services_list", locals: { services: @services } %>
<% end %>

app/views/services/new.html.erb
<div class="bg-white">
  <div class="container p-4">
    <div class="row g-0 justify-content-center align-items-stretch">

      <div class="col-md-5 d-flex flex-column rounded shadow bg-light p-4">
        <h1 class="mb-4 text-center">New Service</h1>
        <%= simple_form_for([@user, @service], html: {data: {turbo: false}}) do |f| %>
          <% if @service.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>
              <ul>
                <% @service.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.input :specie, as: :select, collection: %w[Dog Cat Rodent Bird Reptile Others], prompt: 'Select a specie', label: 'What kind of pet are you sitting?', label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :price, as: :string, label: "What's the price per day?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :description, label: 'Tell us more about the service', label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.hidden_field :latitude %>
            <%= f.hidden_field :longitude %>
            <%= f.input :address,
                        required: true,
                        label: "What is the address where the pet will be cared for?",
                        label_html: { class: 'form-label' },
                        wrapper_html: {
                          data: {
                            controller: 'address-autocomplete',
                            address_autocomplete_api_key_value: ENV['MAPBOX_API_KEY']
                          }
                        },
                        input_html: {
                          data: { address_autocomplete_target: 'address' },
                          class: 'd-none' } %>
          </div>

          <div class="form-group">
            <%= f.input :restrictions, label: "What are your restrictions as a caregiver?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :house_description, label: "Tell us more about your place", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :photo, label: "Please load a photo related to your service", as: :file, required: true, label_html: { class: 'form-label' }, input_html: { class: 'form-control-file', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group text-center d-grid">
            <%= f.button :submit, 'Create Service', class: 'btn btn-warning text-white' %>
          </div>
        <% end %>
      </div>

      <div class="col-md-5 d-flex rounded shadow p-4" style="
        background-image: url('<%= asset_path 'care1.jpeg' %>');
        background-size: cover;
        background-position: center;">
      </div>
    </div>
  </div>
</div>

app/views/services/requests.html.erb
<div class="bg-white my-4">
  <div class="container">
    <h1 class="mb-4">My hired <span class="fw-bold" style= 'color: #FD8522'>Services</span></h1>
    <nav>
			<div class="nav nav-tabs nav-tabs-custom mb-3" id="nav-tab" role="tablist">
        <% list = [
          {name: "Pending", slug: "pending"},
          {name: "Confirmed", slug: "confirmed"},
          {name: "Rejected", slug: "rejected" }
          ] %>

        <% list.each_with_index do |item, index| %>
           <% active = index == 0 ? 'active' : '' %>
           <% aria_select = index == 0 ? 'true' : 'false' %>
            <button
              class="nav-link text-dark <%= active %>"
              id="nav-<%= item[:slug] %>-tab"
              data-bs-toggle="tab"
              data-bs-target="#nav-<%= item[:slug] %>"
              type="button" role="tab"
              aria-controls="nav-<%= item[:slug] %>"
              aria-selected="<%= aria_select %>">
                <%= item[:name] %></button>
        <% end %>

			</div>
		</nav>
    <div class="tab-content" id="nav-tabContent">
			<div
        class="tab-pane fade active show"
        id="nav-pending" role="tabpanel" aria-labelledby="nav-pending-tab">
        <div id="pending-bookings">
          <% unless @bookings_pending.length.zero? %>
            <div class="container-section gap-3">
              <% @bookings_pending.each do |booking| %>
                <%= render 'bookings/booking', booking: booking, user: @user %>
              <% end %>
            </div>
          <% end %>
        </div>
			</div>
			<div
        class="tab-pane fade"
        id="nav-confirmed" role="tabpanel" aria-labelledby="nav-confirmed-tab">
        <div id="confirmed-bookings">
          <% unless @bookings_confirmed.length.zero? %>
            <div class="container-section gap-3">
              <% @bookings_confirmed.each do |booking| %>
                <%= render 'bookings/booking', booking: booking, user: @user %>
              <% end %>
            </div>
          <% end %>
        </div>
			</div>
			<div
        class="tab-pane fade"
        id="nav-rejected" role="tabpanel" aria-labelledby="nav-rejected-tab">
        <div id="rejected-bookings">
          <% unless @bookings_reject.length.zero? %>
            <div class="container-section gap-3">
              <% @bookings_reject.each do |booking| %>
                <%= render 'bookings/booking', booking: booking, user: @user %>
              <% end %>
            </div>
          <% end %>
        </div>
			</div>
		</div>

  </div>
</div>

app/views/services/show.html.erb
<div class="show-container mx-4 mt-2 d-flex flex-column gap-5">
  <div class="row shadow-custom w-75">
  <!-- Imagen a la izquierda -->
  <div class="col-lg-8 d-flex justify-content-center align-items-start">
    <%= cl_image_tag @service.photo.key, crop: :fill, alt: "Service Image", class: "rounded-4 img-fluid w-100", style: "max-height: 300px; object-fit: cover;" %>
  </div>

  <!-- Detalles a la derecha -->
  <div class="col-lg-4 py-3 px-2 d-flex flex-column justify-content-between details-section">
    <header>
      <h2 class="fs-3 text-center mb-2 fw-bold service-title"><%= @service.user.first_name %>'s Pet Sitting Service</h2>
    </header>

    <!-- Información del usuario y calificación -->
    <section class="d-flex justify-content-center align-items-center mb-2 user-info">
      <div class="d-flex align-items-center justify-content-center mx-2">
        <%= cl_image_tag @service.user.photo.key, class: "rounded-circle me-1", width: "30px", height: "30px" %>
        <p class="fs-7 m-0 user-name text-center"><%= @service.user.first_name %> <%= @service.user.last_name %></p>
      </div>
      <div class="d-flex align-items-center justify-content-center mx-2 rating-info">
        <span class=" fs-7 me-1 fw-bold text-center">Rating:</span>
        <span class="rating fs-7 text-center">4.8</span>
      </div>
    </section>

    <!-- Insignia "Top 10 Rated" -->
    <section class="text-center mb-4">
      <span class="badge-custom">Top 10 Rated</span>
    </section>

    <!-- Precio y botón centrados -->
    <footer class="text-center d-flex flex-column justify-content-center align-items-center mt-3">
      <h4 class="m-0 fw-bold price">
        <%= number_to_currency(@service.price) %>
        <span class="fs-6 text-muted">/day</span>
      </h4>
      <% unless @service.user == current_user %>
        <%= link_to 'Book Now', new_service_booking_path(@service), class: 'btn btn-warning btn-sm px-3 text-white book-btn mt-3' %>
      <% end %>
    </footer>
  </div>
</div>

<!-- Sección de información debajo de la tarjeta -->
<div class="container mt-4">
  <div class="row justify-content-center gap-4">

    <!-- House Info -->
    <section class="col-lg-3 col-md-6 detail-info bg-light rounded-3 p-3">
      <h5 class="fw-bold section-title mb-4 text-center"><i class="fa-solid fa-circle-up me-1"></i>House Info</h5>
      <ul class="list-unstyled description" style="font-size: .8rem;">
        <li><i class="fa-solid fa-location-dot icon-custom"></i><strong> Address:</strong> <%= @service.address %></li><br>
        <li><i class="fa-solid fa-book icon-custom"></i><strong> Description:</strong> <%= @service.house_description %></li>
      </ul>
    </section>

    <!-- Service Description -->
    <section class="col-lg-3 col-md-6 detail-info bg-light rounded-3 p-3">
      <h5 class="fw-bold section-title mb-4 text-center"><i class="fa-solid fa-circle-up me-1"></i>Service Description</h5>
      <p class="description" style="font-size: .8rem;"><%= @service.description %></p>
    </section>

    <!-- Service Restrictions -->
    <section class="col-lg-3 col-md-6 detail-info bg-light rounded-3 p-3">
      <h5 class="fw-bold section-title mb-4 text-center"><i class="fa-solid fa-circle-up me-1"></i>Service Restrictions</h5>
      <p class="description" style="font-size: .8rem;"><%= @service.restrictions %></p>
    </section>




        <div class="col-10 px-4">
          <div style="height: 400px;" class="w-full rounded-4"
            data-controller="map"
            data-map-marker-value="<%= @marker.to_json %>"
            data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
    </div>
  </div>
</div>

<div class="container text-center">
  <h3>Recent Reviews</h3>
  <% if @service.recent_reviews.any? %>
    <div class="row my-4">
      <% @service.recent_reviews.each do |review| %>
        <div class="col-4 mb-4">
          <div class="card shadow card-body", style="background-color: white;">
            <div class="d-flex align-items-center mb-2">
              <%= cl_image_tag review.user.photo.key, class: "avatar", alt: "profile photo", crop: :fill, style: "object-fit: cover; height: 40px; width: 40px;" %>
              <div class="d-flex flex-column ms-2">
                <p class="mb-0"><%= review.user.first_name %> <%= review.user.last_name %></p>
              </div>
            </div>
            <div class="d-flex">
              <p>
                <% (1..5).each do |i| %>
                  <% if i <= review.rating %>
                    <i class="fa-solid fa-star" style="color: #fdd835;"></i>
                  <% else %>
                    <i class="fa-solid fa-star" style="color: #dcdce6;"></i>
                  <% end %>
                <% end %>
              </p>&nbsp;&nbsp;
              <p class="text-muted mb-0"><small><%= time_ago_in_words(review.created_at) %> ago</small></p>
            </div>
            <p style="text-align: justify; text-align-last: left;">
              "<%= review.content %>"
            </p>
          </div>
        </div>
      <% end %>
    </div>
  <% else %>
    <p>There are no reviews for this service yet.</p>
  <% end %>
</div>