config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :users

  resources :services do
    resources :bookings
  end

  get "bookings", to: "bookings#index", as: :bookings
  get 'landing', to: 'services#landing'
  get 'requests', to: 'services#requests'
  resources :bookings, only: [] do
    resources :messages, only: [:create]
    resources :reviews, except: [:index]
    member do
      patch :accept
      patch :reject
    end
    resources :activities
  end

  resources :pets
  get 'conversation/:id', to: 'conversations#show', as: :conversation
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  validates :name, presence: true, length: { in: 2..20 }
  validates :specie, inclusion: { in: %w[Dog Cat Rodent Bird Reptile Others] }, presence: true
  validates :description, presence: true, length: { maximum: 500 }
  validates :age, presence: true, length: { maximum: 3 }, numericality: { only_integer: true }
  validates :age, presence: true, length: { maximum: 3 }, numericality: { only_integer: true }
  validates :weight, presence: true, length: { maximum: 5 }, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 30.9, message: 'debe ser un número válido' }
  validates :photo, presence: true
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pets, only: %i[edit update destroy]

  def index
    @pets = Pet.where(user: current_user)
  end

  def new
    @pet = Pet.new
  end

  def edit
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user

    if @pet.save
      redirect_to "/pets", notice: "🎉 Pet#{@pet.name} was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    redirect_to pets_path, notice: "🎉 #{@pet.name} was successfully updated." if @pet.update(pet_params)
  end

  def destroy
    @pet.destroy
    flash[:notice] = "😔 #{@pet.name} was deleted."
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :photo, :specie, :description, :likes, :dislikes, :age, :weight)
  end

  def set_pets
    @pet = Pet.find(params[:id])
  end
end

app/views/pets/_card.html.erb
<div class="col-md-6">
  <div class="card-container h-100">
    <div class="row g-0 bg-warning bg-opacity-25 rounded-top-4">
      <% if pet.photo && pet.photo.key.present? %>
        <div class="col-md-4 rounded-start-4 d-none d-md-block" style="
          background-image: url(<%= cl_image_path(pet.photo.key) %>);
          background-size: cover;
          background-position: top;">
        </div>
      <% else %>
        <div class="col-md-4 rounded-start-4 d-none d-md-flex bg-warning justify-content-center align-items-center fs-2 text-white">
          <i class="fa-solid fa-paw"></i>
        </div>
      <% end %>
      <div class="col-md-8">
        <div class="card-body d-flex flex-column gap-3">
          <div class="d-flex flex-wrap justify-content-between align-items-center">
            <h4 class="card-title m-0 d-none d-md-block flex-grow-1 text-center"><%= pet.name %></h4>
            <div class="d-flex gap-2 d-md-none">
              <% if pet.photo && pet.photo.key.present? %>
                <%= cl_image_tag pet.photo.key, class: "card-box__thumbnail", alt: "#{pet.name}", crop: :fill %>
              <% end %>
              <h4 class="card-title m-0"><%= pet.name %></h4>
            </div>
            <div class="d-flex gap-3">
              <%= link_to edit_pet_path(pet), class: 'card-box__btn' do %>
                <i class="fa-solid fa-pen-to-square"></i>
              <% end %>
              <%= link_to pet, data: { turbo_method: :delete, bs_toggle: "modal", bs_target: "#petModal" }, class: 'px-3 text-orange', style: 'font-size: 20px;'  do %>
                <i class="fa-solid fa-trash"></i>
              <% end %>



<!-- Modal -->
                  <div class="modal fade" id="petModal" tabindex="-1" aria-labelledby="petModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title text-center" id="petModalLabel">Are you sure?</h5>
                          </div>
                          <div class="modal-body">
                            <strong><%= current_user.first_name %></strong> you're about to delete this service
                          </div>
                          <div class="modal-footer">
                            <button type="button" class="btn rounded-pill btn-secondary" data-bs-dismiss="modal">Close</button>
                            <%= link_to pet, data: { turbo_method: :delete }, class: 'px-3', style: 'color: #FD8522; font-size: 24px;'  do %>
                              <span class="btn rounded-pill btn-warning text-white">Delete</span>
                            <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                <!-- Modal -->














            </div>
          </div>

          <div class="d-flex flex-wrap gap-3 justify-content-center">
            <div class="card-box">
              <p class="card-box__content"><%= pet.age %> years</p>
              <p class="card-box__title">Age</p>
            </div>
            <div class="card-box">
              <p class="card-box__content"><%= pet.weight %> kg</p>
              <p class="card-box__title">Weight</p>
            </div>
            <div class="card-box">
              <p class="card-box__content"><%= pet.specie %></p>
              <p class="card-box__title">Specie</p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body px-md-5 d-flex flex-column gap-2">
      <div>
        <h5 class="m-0 text-warning pb-1">About me</h5>
        <p class="m-0"><%= pet.description %></p>
      </div>
      <div>
        <div class="d-flex gap-2 text-warning align-items-center pb-1">
          <i class="fa-solid fa-heart"></i>
          <h6 class="m-0 "> Likes </h6>
        </div>
        <p class="m-0"><%= pet.likes %></p>
      </div>
      <div>
        <div class="d-flex gap-2 text-warning align-items-center pb-1">
          <i class="fa-solid fa-heart-crack"></i>
          <h6 class="m-0 "> Dislikes</h6>
        </div>

        <p class="m-0"><%= pet.dislikes %></p>
      </div>
    </div>
  </div>
</div>

app/views/pets/_form.html.erb
<%= simple_form_for(@pet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.input :specie, as: :select, collection: %w[Dog Cat Rodent Bird Reptile Others], prompt: "Select a specie" %>
    <%= f.input :description %>
    <%= f.input :likes %>
    <%= f.input :dislikes %>
    <%= f.input :age %>
    <%= f.input :weight %>
  </div>

  <div class="form-actions text-center">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<div class="bg-white">
  <div class="container p-4">
    <div class="row g-0 justify-content-center align-items-stretch">

      <div class="col-md-5 d-flex flex-column rounded shadow bg-light p-4">
        <h3 class="mb-4 text-center">Edit this pet's information</h3>
        <%= simple_form_for(@pet) do |f| %>
          <% if @pet.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
              <ul>
                <% @pet.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.input :name, as: :string, label: "What is your pet's name?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :specie, as: :select, collection: %w[Dog Cat Rodent Bird Reptile Others], prompt: 'Select a specie', label: "What's your pet specie?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="row form-group">
            <div class="col-lg-6">
              <%= f.input :age, label: "How old is your pet?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
            </div>

            <div class="col-lg-6">
              <%= f.input :weight, label: "What's your pet's weight?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
            </div>
          </div>

          <div class="form-group">
            <%= f.input :photo, label: "Please load a photo related to your pet", as: :file, required: true, label_html: { class: 'form-label' }, input_html: { class: 'form-control-file', style: 'font-size: 14px;' }%>
          </div>

          <div class="form-group">
            <%= f.input :description, :as => :text, label: "How would you describe your pet?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;'} %>
          </div>

          <div class="form-group">
            <%= f.input :likes, :as => :text, label: "What things does your pet like?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
          <%= f.input :dislikes, :as => :text, label: "What things does your pet dislikes?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group text-center d-grid">
            <%= f.button :submit, 'Save', class: 'btn btn-warning text-white' %>
          </div>
        <% end %>
      </div>

      <div class="col-md-5 d-flex rounded shadow p-4" style="
        background-image: url(<%= asset_path 'cat_and_dogs.jpg' %>);
        background-size: cover;
        background-position: center;">
      </div>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="container mb-5">

   <div class="d-flex justify-content-between align-items-center my-4">
    <h1 class="">My <span class="fw-bold" style= 'color: #FD8522'>Pets</span></h1>
    <%= link_to new_pet_path, class: 'mt-3 btn text-white rounded-pill px-4 py-2', style: "background-color: #FD8522;" do %>
      <i class="fa-solid fa-plus"></i> Add New Pet
    <% end %>
  </div>

  <% if @pets.any? %>
    <div class="row g-4">
      <% @pets.each do |pet| %>
        <%= render partial: "card", locals: { pet: pet } %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<div class="bg-white">
  <div class="container p-4">
    <div class="row g-0 justify-content-center align-items-stretch">

      <div class="col-md-5 d-flex flex-column rounded shadow bg-light p-4">
        <h1 class="mb-4 text-center">Add a new pet</h1>
        <%= simple_form_for(@pet) do |f| %>
          <% if @pet.errors.any? %>
            <div id="error_explanation" class="alert alert-danger">
              <h2><%= pluralize(@pet.errors.count, "error") %> prohibited this pet from being saved:</h2>
              <ul>
                <% @pet.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-group">
            <%= f.input :name, as: :string, label: "What is your pet's name?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
            <%= f.input :specie, as: :select, collection: %w[Dog Cat Rodent Bird Reptile Others], prompt: 'Select a specie', label: 'Whats your pet specie?', label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="row form-group">
            <div class="col-lg-6">
              <%= f.input :age, label: "How old is your pet?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
            </div>

            <div class="col-lg-6">
              <%= f.input :weight, label: "What's your pet's weight?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
            </div>
          </div>

          <div class="form-group">
            <%= f.input :photo, label: "Please load a photo related to your pet", as: :file, required: true, label_html: { class: 'form-label' }, input_html: { class: 'form-control-file', style: 'font-size: 14px;' }%>
          </div>

          <div class="form-group">
            <%= f.input :description, :as => :text, label: "How would you describe your pet?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;'} %>
          </div>

          <div class="form-group">
            <%= f.input :likes, :as => :text, label: "What things does your pet like?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group">
          <%= f.input :dislikes, :as => :text, label: "What things does your pet dislikes?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>
          </div>

          <div class="form-group text-center d-grid">
            <%= f.button :submit, 'Create Pet', class: 'btn btn-warning text-white' %>
          </div>
        <% end %>
      </div>

      <div class="col-md-5 d-flex rounded shadow p-4" style="
        background-image: url(<%= asset_path 'cat_and_dogs.jpg' %>);
        background-size: cover;
        background-position: center;">
      </div>
    </div>
  </div>
</div>