config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :users

  resources :services do
    resources :bookings
  end

  get "bookings", to: "bookings#index", as: :bookings
  get 'landing', to: 'services#landing'
  get 'requests', to: 'services#requests'
  resources :bookings, only: [] do
    resources :messages, only: [:create]
    resources :reviews, except: [:index]
    member do
      patch :accept
      patch :reject
    end
    resources :activities
  end

  resources :pets
  get 'conversation/:id', to: 'conversations#show', as: :conversation
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :activities, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :messages
  belongs_to :pet
  belongs_to :service

  validates :start_date, :end_date, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service, except: %i[accept reject index]
  before_action :set_booking, only: %i[show]

  def index
    @bookings = Booking.joins(pet: :user).where(pets: { user_id: current_user.id })
    @user = User.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = @service.bookings.new(booking_params)
    @booking.status = "pending"
    if @booking.save
      redirect_to service_booking_path(@service, @booking), notice: 'Booking was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def total_days(booking)
    return 0 unless booking.start_date && booking.end_date

    (booking.end_date - booking.start_date).to_i
  end

  def total_price(booking)
    days = total_days(booking)
    return booking.service.price if days.zero?

    return (booking.service.price * total_days(booking))
  end

  def show
    @total_price = total_price(@booking)
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: "confirmed")

    respond_to do |format|
      format.turbo_stream { render "bookings/update_status" }
      format.html { redirect_to some_path, notice: "Booking was successfully confirmed." }
    end
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.update(status: "rejected")

    respond_to do |format|
      format.turbo_stream { render "bookings/update_status" }
      format.html { redirect_to some_path, notice: "Booking was successfully rejected." }
    end
  end

  private

  def set_service
    @service = Service.find(params[:service_id])
  end

  def set_booking
    @booking = @service.bookings.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :message, :pet_id, :status)
  end
end

app/views/bookings/_booking.html.erb
<div
  class="card-custom card bg-white shadow-lg rounded-4 p-0 h-100"
  id="booking_<%= booking.id %>">
  <div class="border-bottom p-3 d-flex flex-column flex-sm-row justify-content-between align-sm-items-center">
    <p class="m-0 text-orange fs-7 fw-medium">
      <%= booking.created_at.strftime("%B %d, %Y") %>
    </p>
    <p class="m-0">
      <span class="fw-medium">The service is </span>
      <%
        def getClass(status)
          return "text-warning" if status == "pending"

          status == "confirmed" ? 'text-success' : 'text-danger'
        end
      %>
      <strong class="<%= getClass(booking.status) %>">
        <%= booking.status.upcase %>
      </strong>
    </p>
  </div>
  <div class="card-body">
    <div class="row g-3">
      <div class="col-3 d-flex justify-content-center align-items-start">
        <%= cl_image_tag booking.service.photo.key, class: "w-100" %>
      </div>
      <div class="col-9 d-flex flex-column justify-content-center gap-2">
        <p class="m-0">
          <span class="fw-bold fs-7 text-secondary">
            <i class="fa-regular fa-user"></i>
            &nbsp; Hired by:</span>
          <%= booking.pet.user.first_name %> <%= booking.pet.user.last_name %></p>
        <p class="m-0">
          <span class="fw-bold fs-7 text-secondary">
            <i class="fa-solid fa-paw"></i>&nbsp; To take care of:
          </span>
          <%= booking.pet.name %> (<%= booking.pet.specie %>)</p>
        <p class="m-0">
          <span class="fw-bold fs-7 text-secondary">Price per day:</span>
          $<%= booking.service.price %></p>

      </div>
      <div class="col-12 d-flex flex-column justify-content-center gap-3">
        <p class="m-0">
          "<%= booking.pet.description %>"
        </p>
        <p class="m-0">
          <span class="fw-bold fs-7 text-secondary">
            <i class="fa-regular fa-calendar"></i>&nbsp; From:
          </span>
          <%= booking.start_date.strftime("%B %d, %Y") %>
          <span class="fw-bold fs-7 text-secondary">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To:</span>
          <%= booking.end_date.strftime("%B %d, %Y") %>
        </p>

        <p class="m-0 lh-base">
          <span class="fw-bold fs-7 text-secondary d-block pb-1">
            <i class="fa-solid fa-location-dot"></i>&nbsp; The address where you will provide the service in is:
          </span>
          <%= booking.service.address %>
        </p>
        <p class="m-0 lh-base">"<%= booking.message %>"</p>
      </div>
    </div>
  </div>

  <% if booking.status == "pending" %>
    <div data-controller="tab-switch" class="d-flex flex-column flex-sm-row justify-content-center gap-3 border-top p-3">
      <%= button_to 'Confirm Booking',
        accept_booking_path(booking),
        method: :patch,
        data: {
          turbo_action: "replace",
          action: "turbo:submit-end->tab-switch#changeTab"
        },
        class: 'btn btn-success rounded-pill px-4 py-2 text-white w-100' %>

        <%= button_to 'Reject Booking',
          reject_booking_path(booking),
          method: :patch,
          data: {
            turbo_confirm: 'Are you sure?',
            turbo_action: "replace",
            action: "turbo:submit-end->tab-switch#changeTab" },
          class: 'btn btn-danger rounded-pill px-4 py-2 text-white w-100' %>
    </div>
  <% end %>

  <%# LINK_TO CHAT %>
  <% if current_user != @user && booking.status == "confirmed" %>
    <div class="px-3 pb-3 d-flex justify-content-end gap-3" data-controller="tooltip">
      <%= link_to booking_activities_path(booking), class: 'rounded-circle px-2 py-1 text-white bg-secondary bg-opacity-75 fs-5', data: { action: "click->tooltip#hiddenTooltip", tooltip_target: "tooltip", bs_toggle: "tooltip", bs_title: "View pet's calendar"} do %>
          <i class="fa-regular fa-calendar-days"></i>
        <% end %>
      <%= link_to conversation_path(booking.pet.user.id, booking_id: booking.id), class: "rounded-circle px-2 py-1 text-white bg-orange bg-opacity-75 fs-5", data: { bs_toggle: "tooltip", bs_title: "Chat with #{booking.pet.user.first_name}" }  do %>
        <i class="fa-regular fa-comments"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/bookings/_booking_card.html.erb
<div class="card-custom card bg-white shadow-lg rounded-4 my-3">
  <div class="border-bottom p-3 d-flex flex-column flex-sm-row justify-content-between align-sm-items-center">
    <p class="m-0 text-orange fs-7 fw-medium">
      <%= booking.created_at.strftime("%B %d, %Y") %>
    </p>
     <p class="m-0">
      <span class="fw-medium">The service is </span>
      <%
        def getClass(status)
          return "text-warning" if status == "pending"

          status == "confirmed" ? 'text-success' : 'text-danger'
        end
      %>
      <strong class="<%= getClass(booking.status) %>">
        <%= booking.status.upcase %>
      </strong>
    </p>
  </div>
  <div class="card-body bg-white rounded-4">
    <div class="row g-3">
      <div class="col-4 d-flex justify-content-start">
        <%= cl_image_tag booking.service.photo.key, class: "w-100", style: "object-fit: contain;", crop: :fill %>
      </div>
      <div class="col-8 d-flex flex-column justify-content-center gap-3">
        <p class="m-0">
          <span class="fw-bold text-secondary">
            <%= booking.service.user.first_name %>
            <%= booking.service.user.last_name %>
          </span>
          is taking care of <%= booking.pet.name %>
        </p>

        <p class="m-0">
          <span class="fw-bold fs-7 text-secondary">Price per day:</span>
          $<%= booking.service.price %></p>

        <p class="m-0">
          <span class="fw-bold fs-7 text-secondary">
            <i class="fa-solid fa-phone"></i>&nbsp;
            <%= booking.service.user.first_name %>'s phone:
          </span>
          <%= booking.service.user.phone_number %>
        </p>

      </div>
      <div class="col-12 d-flex flex-column justify-content-center gap-3">
        <p class="m-0 lh-base">"<%= booking.service.description %>"</p>
        <p class="m-0">
          <span class="fw-bold fs-7 text-secondary">
            <i class="fa-regular fa-calendar"></i>
          &nbsp; From:</span>
          <%= booking.start_date.strftime("%B %d, %Y") %>
          <span class="fw-bold fs-7 text-secondary">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To:</span>
          <%= booking.end_date.strftime("%B %d, %Y") %>
        </p>
        <p class="m-0 lh-base">
          <span class="fw-bold fs-7 text-secondary d-block pb-1">
            <i class="fa-solid fa-location-dot"></i>&nbsp;
            <%= booking.service.user.first_name %>'s address:
          </span>
          <%= booking.service.address %></p>
      </div>
    </div>
  </div>
  <% if booking.status == 'confirmed' %>
    <div class="d-flex flex-column flex-sm-row justify-content-end gap-3 border-top p-3">
      <div class="d-flex gap-3" data-controller="tooltip">
        <% if current_user != @user %>
          <%# LINK_TO CHAT %>
          <%= link_to conversation_path(booking.pet.user.id,
          booking_id: booking.id), class: "rounded-circle px-2 py-1 text-white bg-orange bg-opacity-75 fs-5", data: { action: "click->tooltip#hiddenTooltip", tooltip_target: "tooltip", bs_toggle: "tooltip", bs_title: "Chat with #{booking.service.user.first_name}" }  do %>
            <i class="fa-regular fa-comments"></i>
          <% end %>
        <% end %>
        <%= link_to booking_activities_path(booking), class: 'rounded-circle px-2 py-1 text-white bg-secondary bg-opacity-75 fs-5', data: { action: "click->tooltip#hiddenTooltip", tooltip_target: "tooltip", bs_toggle: "tooltip", bs_title: "View pet's calendar"} do %>
          <i class="fa-regular fa-calendar-days"></i>
        <% end %>
        <%= link_to new_booking_review_path(booking), class: 'rounded-circle px-2 py-1 text-white bg-primary bg-opacity-75 fs-5', data: { action: "click->tooltip#hiddenTooltip", tooltip_target: "tooltip", bs_toggle: "tooltip", bs_title: "Create a review for this service" } do %>
          <i class="fa-solid fa-paw"></i>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div class="bg-white">
  <div class="container pb-4">
    <h1 class="my-4">Booked services for your <span class="fw-bold text-orange">Pets</span></h1>
    <div class="container-section">
      <% @bookings.reverse.each do |booking| %>
        <%= render 'bookings/booking_card', booking: booking %>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
 <div class="booking-container">
    <div class="row" data-controller="hello">
      <!-- Left Column -->
      <div class="col-md-7" >
        <h2 class="booking-title text-center">Just one more step</h2>
          <%= form_with(model: [@service, @booking], local: true) do |form| %>
            <% if @booking.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
                <ul>
                  <% @booking.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          <!-- Start and End Date -->
          <div class="row">
            <div class="col-md-6 form-group">
              <%= form.label :start_date %>
              <%= form.date_field :start_date, style: 'font-size: 14px;', class: "form-control", id: "start-date", data: { target: "hello.startDate", action: "input->hello#calculateDays" }, min: Date.today %>
            </div>
            <div class="col-md-6 form-group">
              <%= form.label :end_date%>
              <%= form.date_field :end_date,style: 'font-size: 14px;', class: "form-control", id: "end-date", data: { target: "hello.endDate", action: "input->hello#calculateDays" }, min: Date.today %>
            </div>
          </div>

          <!-- Pet selection -->


          <select name="booking[pet_id]"
            id="pet_id" class="form-control mb-2 fs-7"
            data-target="hello.petSelect"
            data-action="change->hello#updatePetName">
            <option value="">Select a pet</option>
            <% Pet.where(user: current_user).each do |pet| %>
              <option value="<%= pet.id %>" data-photo="<%= cl_image_path(pet.photo.key) %>"> <%= pet.name %> </option>
            <% end %>
          </select>



          <!-- Message -->
          <div class="form-group mt-2">
            <%= form.label "Write a message for the pet sitter:", class: "mb-1 mt-2" %>
            <%= form.text_area :message, class: "form-control", style: 'font-size: 14px;'%>
          </div>

          <!-- Submit Button -->
          <%= form.submit 'Create Booking', class:"btn-submit" %>
        <% end %>
        <div class="booking-back-links mt-2">
         <%= link_to 'Back to Service Details', service_path(@service) %>
        </div>
      </div>

      <!-- Right Column -->
      <div class="col-md-5 mt-5">
        <!-- Reservation Box -->
        <div class="reservation-box mb-4">
          <p class="d-none"> Price per day: <strong data-target="hello.price"><%= @service.price %></strong></p>
          <span data-target="hello.output">0</span><span> days</span>
          <p>Total price: $<strong data-target="hello.totalPrice"></strong></p>
        </div>

        <!-- Info Box -->
        <div class="info-box h-50">
        <div id="petPhotoDisplay" class="pet-photo-container"> <!-- Initial Image (Optional) --> <img id="petPhoto" src="<%= cl_image_path("https://res.cloudinary.com/dgbg8nxyq/image/upload/v1726517312/shadow_yw4zen") %>" /> </div>
          <p id="petNameDisplay"></p>
        </div>
      </div>

    </div>
</div>

app/views/bookings/show.html.erb
<div class="container mb-5 booking-detail">

  <div class="text-center d-flex flex-column justify-content-center align-items-center gap-3">
    <div class="icon-box">
      <div class="icon-box__context">
        <i class="fa-solid fa-paw"></i>
      </div>
    </div>
    <h1 class="m-0">Request created!</h1>
    <p class="m-0 text-secondary">You need to wait for the caregiver to approve your service request. 🎉</p>
  </div>

  <h2 class="m-0 fs-5 ">Booking details</h2>

  <div class="row g-4">
    <div class="col-md-7 col-lg-5">
      <div class="bg-white border border-warning rounded-4 shadow">
        <h3 class="text-warning fs-6 m-0 p-3 bg-warning bg-opacity-25 border-warning border-bottom">Summary</h3>
        <div class="d-flex flex-column gap-3 p-3">

          <p class="m-0">
            <span class="fw-medium fs-7 ">
              <i class="fa-regular fa-calendar"></i>&nbsp; From:
            </span>
            <%= @booking.start_date.strftime("%B %d, %Y") %>
            <span class="fw-medium fs-7 "> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; To:</span>
            <%= @booking.end_date.strftime("%B %d, %Y") %>
          </p>

          <div>
            <p class="fw-medium fs-7  m-0">
              <i class="fa-regular fa-comment"></i>&nbsp; Message: </p>
            <p class="m-0"><%= @booking.message %></p>
          </div>

          <div>
            <p class="fw-medium fs-7  m-0">
              <i class="fa-solid fa-location-dot"></i>&nbsp; The address: </p>
            <p class="m-0"><%= @booking.service.address %></p>
          </div>

          <div>
            <p class="fw-medium fs-7  m-0">
              <i class="fa-regular fa-credit-card"></i>&nbsp; Price per day: </p>

            <p class="m-0"><i class="fa-solid fa-dollar-sign"></i> <%= @booking.service.price  %></p>
          </div>
        </div>
        <div class="fs-6 m-0 px-3 py-2 bg-warning bg-opacity-50 border-warning border-top d-flex justify-content-between align-items-center fw-bold">
          <p class="m-0">Total</p>
          <p class="m-0">
            <i class="fa-solid fa-dollar-sign"></i></i>
            <%= @total_price %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-5 col-lg-3">
      <div class="bg-white border border-warning rounded-4 shadow card-container">
      <h3 class="text-warning fs-6 m-0 p-3 bg-warning bg-opacity-25 border-warning border-bottom">Pet</h3>
        <div class="d-flex flex-column gap-3 p-3">

          <div class="d-flex align-items-center gap-2">
            <% if @booking.pet.photo && @booking.pet.photo.key.present? %>
                <%= cl_image_tag @booking.pet.photo.key, class: "card-box__thumbnail", alt: "#{@booking.pet.name}", crop: :fill %>
            <% end %>
            <h4 class="card-title m-0 fs-6"><%= @booking.pet.name %></h4>
          </div>

          <div class="d-flex flex-wrap gap-3">
            <div class="card-box__invert">
              <p class="card-box__content"><%= @booking.pet.age %> years</p>
              <p class="m-0  fs-7">Age</p>
            </div>
            <div class="card-box__invert">
              <p class="card-box__content"><%= @booking.pet.weight %> kg</p>
              <p class="m-0  fs-7">Weight</p>
            </div>
            <div class="card-box__invert">
              <p class="card-box__content"><%= @booking.pet.specie %></p>
              <p class="m-0  fs-7">Specie</p>
            </div>
          </div>

          <div>
            <div class="d-flex gap-2 fw-medium fs-7  align-items-center pb-1">
              <i class="fa-solid fa-heart"></i>
              <h6 class="m-0"> Likes </h6>
            </div>
            <p class="m-0"><%= @booking.pet.likes %></p>
          </div>

          <div>
            <div class="d-flex gap-2 fw-medium fs-7  align-items-center pb-1">
              <i class="fa-solid fa-heart-crack"></i>
              <h6 class="m-0 "> Dislikes</h6>
            </div>

            <p class="m-0"><%= @booking.pet.dislikes %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-7 col-lg-4">
      <div class="bg-white border border-warning rounded-4 shadow card-container">
        <h3 class="text-warning fs-6 m-0 p-3 bg-warning bg-opacity-25 border-warning border-bottom">Service</h3>
        <div class="d-flex flex-column gap-3 p-3">

          <div>
            <p class="fw-medium fs-7  m-0">
              <i class="fa-solid fa-user"></i>&nbsp; By: </p>

            <div class="d-flex align-items-center gap-2">
              <% if @booking.service.user.photo &&  @booking.service.user.photo.key.present? %>
                <%= cl_image_tag  @booking.service.user.photo.key, class: "card-box__thumbnail", alt: "#{ @booking.service.user.first_name}", crop: :fill %>
              <% end %>
              <p class="m-0"><%= @booking.service.user.first_name %> <%= @booking.service.user.last_name %></p>
            </div>
          </div>

          <div>
            <p class="fw-medium fs-7  m-0">
              <i class="fa-solid fa-triangle-exclamation"></i>&nbsp; Restrictions: </p>
            <p class="m-0"><%= @booking.service.restrictions %></p>
          </div>

          <div>
            <p class="fw-medium fs-7  m-0">
              <i class="fa-solid fa-house"></i>&nbsp; Place description: </p>
            <p class="m-0"><%= @booking.service.house_description %></p>
          </div>

        </div>
      </div>
    </div>

  </div>

</div>

app/views/bookings/update_status.turbo_stream.erb
<%= turbo_stream.replace "flash" do %>
  <div class="alert alert-success">
    Booking was successfully <%= @booking.status %>.
  </div>
<% end %>

<%= turbo_stream.remove "booking_#{@booking.id}" %>
<% status = @booking.status %>

<%= turbo_stream.append "#{status}-bookings" do %>
  <div class="container-section gap-3">
    <%= render partial: "bookings/booking", locals: { booking: @booking } %>
  <div>
<% end %>