config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  root to: "pages#home"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :users

  resources :services do
    resources :bookings
  end

  get "bookings", to: "bookings#index", as: :bookings
  get 'landing', to: 'services#landing'
  get 'requests', to: 'services#requests'
  resources :bookings, only: [] do
    resources :messages, only: [:create]
    resources :reviews, except: [:index]
    member do
      patch :accept
      patch :reject
    end
    resources :activities
  end

  resources :pets
  get 'conversation/:id', to: 'conversations#show', as: :conversation
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :booking
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_booking, only: %i[index new create edit]
  before_action :set_activity, only: %i[edit update destroy]

  def index
    @start_date = @booking.start_date
    @end_date = @booking.end_date
    @activities = @booking.activities.group_by { |activity| activity.date }
  end


  def new
    @activity = Activity.new
    @start_date = @booking.start_date
    @end_date = @booking.end_date
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.booking_id = @booking.id
    if @activity.save
      redirect_to booking_activities_path, notice: 'Actividad creada con éxito.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      redirect_to booking_activities_path, notice: 'Activity was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @activity.destroy!
    redirect_to booking_activities_path, notice: 'Activity was successfully deleted.'
  end

  private

  def set_activity
    @activity = Activity.find(params[:id])
  end

  def activity_params
    params.require(:activity).permit(:name, :description, :start_time, :end_time, :date)
  end

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end
end

app/views/activities/edit.html.erb
<div class="bg-white">
  <div class="container p-4">
    <div class="row g-0 justify-content-center align-items-stretch">

      <div class="col-md-5 d-flex flex-column rounded shadow bg-light p-4">
        <h1 class="mb-4 text-center">Edit this Activity</h1>
        <%= simple_form_for([@booking, @activity]) do |form| %>
          <%= form.input :booking_id, as: :hidden, input_html: { value: params[:booking_id] } %>

          <%= form.input :name, label: "What's the name of the activity?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <%= form.input :description, as: :text, label: "Describe the activity", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <%= form.input :start_time, as: :time, label: "What time does the activity start?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <%= form.input :end_time, as: :time, label: "What time does the activity end?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <%= form.input :date, as: :date, label: "When is the activity happening?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <div class="form-group text-center d-grid">
            <%= form.button :submit, class: 'btn btn-warning text-white' %>
          </div>
        <% end %>
      </div>

      <div class="col-md-5 d-flex rounded shadow p-4" style="
        background-image: url('<%= asset_path 'play.jpg' %>');
        background-size: cover;
        background-position: center;">
      </div>
    </div>
  </div>
</div>

app/views/activities/index.html.erb
<h1 class="text-center">Pet's Calendar</h1>
<div class="container">
  <p class="text-center"><strong>Set the calendars for:&nbsp;</strong>
  <%= cl_image_tag @booking.pet.photo.key, class: "avatar", alt: "dropdown menu", crop: :fill, style: "object-fit: cover; height: 40px;" %> <%= @booking.pet.name %></p>
</div>
<div class="container my-4">
  <div class="table-responsive">
    <table class="table table-bordered shadow-sm" style="width: 100%;">
      <thead>
      </thead>
      <tbody>
        <% (@start_date..@end_date).each_slice(7).each_with_index do |dates_row, index| %>
          <tr style="--column-count: <%= dates_row.length %>;">
            <% dates_row.each do |date| %>
              <th class="text-center" style="color: white; background-color: #fd8522;">
                <h5><%= date.strftime("%d/%m/%y") %></h5>
              </th>
            <% end %>
          </tr>

          <tr class="<%= index.even? ? 'bg-warning' : '' %>" style="--column-count: <%= dates_row.length %>;">
            <% dates_row.each do |date| %>
              <td>
                <% activities_for_day = @activities[date] || [] %>
                <% if activities_for_day.any? %>
                  <% activities_for_day.each do |activity| %>
                    <div class="activity">
                      <h5 class="mb-2"><strong><i class="fa-solid fa-paw"></i>&nbsp;&nbsp;<%= activity.name %></strong></h5>
                      <p class="mb-2"><%= activity.description %></p>
                      <p class="mb-2"><%= activity.start_time.strftime("%H:%M") %> - <%= activity.end_time.strftime("%H:%M") %></p>
                      <div class="d-flex justify-content-center mb-3">
                        <%= link_to edit_booking_activity_path(@booking, activity), class: 'px-3 me-2', style: 'color: black; font-size: 20px;' do %>
                          <i class="fa-solid fa-pen-to-square"></i>
                        <% end %>
                        <%= link_to booking_activity_path(@booking, activity), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: 'px-3', style: 'color: black; font-size: 20px;'  do %>
                          <i class="fa-solid fa-trash"></i>
                        <% end %>
                    </div>
                    </div>
                  <% end %>
                <% else %>
                  <p>No activities for today.</p>
                <% end %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="text-center">
    <%= link_to new_booking_activity_path, class: 'mb-4 btn text-white rounded-pill px-4 py-2', style: "background-color: #FD8522; transition: transform 0.3s; transform: scale(1);", onmouseover: "this.style.transform='scale(1.1)';", onmouseout: "this.style.transform='scale(1)';" do %>
      <i class="fa-solid fa-plus"></i> Add New Activity
    <% end %>
  </div>

</div>

app/views/activities/new.html.erb
<div class="bg-white">
  <div class="container p-4">
    <div class="row g-0 justify-content-center align-items-stretch">

      <div class="col-md-5 d-flex flex-column rounded shadow bg-light p-4">
        <h1 class="mb-4 text-center">New Activity</h1>
        <%= simple_form_for([@booking, @activity]) do |form| %>
          <%= form.input :booking_id, as: :hidden, input_html: { value: params[:booking_id] } %>

          <%= form.input :name, label: "What's the name of the activity?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <%= form.input :description, as: :text, label: "Describe the activity", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <%= form.input :start_time, as: :time, label: "What time does the activity start?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <%= form.input :end_time, as: :time, label: "What time does the activity end?", label_html: { class: 'form-label' }, input_html: { class: 'form-control', style: 'font-size: 14px;' } %>

          <%= form.label :date, "When is the activity happening?", class: 'form-label' %>
          <%= form.date_field :date, class: 'form-control mb-3', style: 'font-size: 14px;', min: @start_date.strftime('%Y-%m-%d'), max: @end_date.strftime('%Y-%m-%d') %>

          <div class="form-group text-center d-grid">
            <%= form.button :submit, class: 'btn btn-warning text-white' %>
          </div>
        <% end %>
      </div>

      <div class="col-md-5 d-flex rounded shadow p-4" style="
        background-image: url('<%= asset_path 'play.jpg' %>');
        background-size: cover;
        background-position: center;">
      </div>
    </div>
  </div>
</div>